service: s3-pdf2json-lambda-function
provider:
  name: aws
  runtime: python3.7
  region: ap-south-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_joke:
    handler: handler.json_resume
    events:
      - http:
          path: joke
          method: get

plugins:
  - serverless-python-requirements
